/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_study_pluto_jnitest_ExampleUnitTest */

#ifndef _Included_com_study_pluto_jnitest_ExampleUnitTest
#define _Included_com_study_pluto_jnitest_ExampleUnitTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_study_pluto_jnitest_ExampleUnitTest
 * Method:    test
 * Signature: (ILjava/lang/String;F)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_study_pluto_jnitest_ExampleUnitTest_test
  (JNIEnv *, jobject, jint, jstring, jfloat);

#ifdef __cplusplus
}
#endif
#endif
